apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{deploymentName}}-canary"
  labels:
    name: "{{deploymentName}}"
  annotations:
    kubernetes.io/ingress.class: "nginx"

    # Enable canary and send 10% of traffic to version 2
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "{{percentCanary}}"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: "{{deploymentName}}-canary"
          servicePort: 80
