apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{deploymentName}}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - backend:
          serviceName: "{{deploymentName}}-{{productionSlot}}"
          servicePort: 80