apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      name: helloworld
  replicas: 2
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
        - name: helloworld
          # enter the path to your image, be sure to include the correct region prefix
          image: phx.ocir.io/ax022wvgmjpq/bluegreen:1.0.0
          ports:
            - containerPort: 80
      imagePullSecrets:
        # enter the name of the secret you created
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc-primary
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: helloworld
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - secretName: tls-secret
  rules:
    - http:
        paths:
          - backend:
              serviceName: helloworld-svc-primary
              servicePort: 80