apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{deploymentName}}"
spec:
  selector:
    matchLabels:
      name: "{{deploymentName}}"
  replicas: 2
  template:
    metadata:
      labels:
        name: "{{deploymentName}}"
    spec:
      containers:
        - name: "{{deploymentName}}"
          # enter the path to your image, be sure to include the correct region prefix
          image: "{{image}}"
          ports:
            - containerPort: 80
      imagePullSecrets:
        # enter the name of the secret you created
        - name: "{{imagePullSecret}}"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{deploymentName}}"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: "{{deploymentName}}"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{deploymentName}}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - secretName: tls-secret
  rules:
    - http:
        paths:
          - backend:
              serviceName: "{{deploymentName}}"
              servicePort: 80